apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: vendor-invoice

data:

  DATABASE_HOST: postgres

  DATABASE_PORT: "5432"

  DATABASE_NAME: vendor_invoice_db

  REDIS_HOST: redis

  REDIS_PORT: "6379"

  MAIL_SERVER: smtp.gmail.com

  MAIL_PORT: "587"

  ENVIRONMENT: production