apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: vendor-invoice

type: Opaque

data:

  POSTGRES_USER: cG9zdGdyZXM=

  POSTGRES_PASSWORD: cG9zdGdyZXM=

  SECRET_KEY: Z2l0aHVia2V5

  MAIL_USERNAME: ZGVtb0BleGFtcGxlLmNvbQ==

  MAIL_PASSWORD: cGFzc3dvcmQ=

  MAIL_FROM: ZGVtb0BleGFtcGxlLmNvbQ==