"""add fraud fields

Revision ID: 4045acc23c3b
Revises: 9c5fb62d1ccc
Create Date: 2026-07-31 23:49:59.357081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4045acc23c3b'
down_revision: Union[str, Sequence[str], None] = '9c5fb62d1ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('fraud_detected', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('duplicate_invoice', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'duplicate_invoice')
    op.drop_column('invoices', 'fraud_detected')
    op.drop_column('invoices', 'risk_level')
    op.drop_column('invoices', 'risk_score')
    # ### end Alembic commands ###
