"""add OCR fields to invoices

Revision ID: 4d279e491bc1
Revises: c18c7828856a
Create Date: 2026-07-30 16:41:08.306951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d279e491bc1'
down_revision: Union[str, Sequence[str], None] = 'c18c7828856a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('ocr_confidence', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'created_at')
    op.drop_column('invoices', 'ocr_confidence')
    op.drop_column('invoices', 'extracted_text')
    op.drop_column('invoices', 'file_name')
    # ### end Alembic commands ###
