"""add approval history

Revision ID: 747d78e77f99
Revises: 371960b3093c
Create Date: 2026-07-29 18:52:30.707542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747d78e77f99'
down_revision: Union[str, Sequence[str], None] = '371960b3093c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invoices', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invoices', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
