"""add extracted invoice fields

Revision ID: 9c5fb62d1ccc
Revises: 82f069003f42
Create Date: 2026-07-31 20:40:40.856844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5fb62d1ccc'
down_revision: Union[str, Sequence[str], None] = '82f069003f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('vendor_name', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('extracted_invoice_number', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('extracted_amount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('extracted_invoice_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('extracted_due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'extracted_due_date')
    op.drop_column('invoices', 'extracted_invoice_date')
    op.drop_column('invoices', 'extracted_amount')
    op.drop_column('invoices', 'extracted_invoice_number')
    op.drop_column('invoices', 'vendor_name')
    # ### end Alembic commands ###
