"""add invoice date and due date

Revision ID: bf2ed34b81ed
Revises: 29afbe45e495
Create Date: 2026-07-29 01:27:49.906018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2ed34b81ed'
down_revision: Union[str, Sequence[str], None] = '29afbe45e495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'due_date')
    op.drop_column('invoices', 'invoice_date')
    # ### end Alembic commands ###
