"""add created_by to invoices

Revision ID: ce932b0320ed
Revises: 940daf0b7e3c
Create Date: 2026-07-31 19:51:55.894003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce932b0320ed'
down_revision: Union[str, Sequence[str], None] = '940daf0b7e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'created_by')
    # ### end Alembic commands ###
