"""add invoice processing fields

Revision ID: f9c70c24e6b4
Revises: d76f2b116540
Create Date: 2026-07-30 19:14:54.972895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c70c24e6b4'
down_revision: Union[str, Sequence[str], None] = 'd76f2b116540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('processing_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'processing_completed_at')
    op.drop_column('invoices', 'processing_started_at')
    # ### end Alembic commands ###
