"""add currency and dates to invoices

Revision ID: bea31f4621ec
Revises: dfbeac35a4cf
Create Date: 2026-07-29 01:21:09.582215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea31f4621ec'
down_revision: Union[str, Sequence[str], None] = 'dfbeac35a4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'currency')
    # ### end Alembic commands ###
