"""create approval history table

Revision ID: f0c44b25c18c
Revises: f9c70c24e6b4
Create Date: 2026-07-30 19:55:35.297362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c44b25c18c'
down_revision: Union[str, Sequence[str], None] = 'f9c70c24e6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_history', 'comment',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('vendors', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_constraint(op.f('vendors_email_key'), 'vendors', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('vendors_email_key'), 'vendors', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.drop_column('vendors', 'created_at')
    op.alter_column('approval_history', 'comment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
