apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: vendor-invoice

type: Opaque

stringData:

  SECRET_KEY: your-secret-key

  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/vendor_invoice_db